library(zellkonverter)
library(SingleCellExperiment)
library(Matrix)
sce <- readH5AD("AIDA_RawCounts_ETHNICITY_50kPerGroup.h5ad", use_hdf5=FALSE)
cat("dim:", dim(sce), "\n")
m <- assay(sce, 1)
cat("Sum:", sum(m), "\n")
lib <- Matrix::colSums(m)
cat("Lib mean:", mean(lib), "  median:", median(lib), "\n")
cat("First 5 lib sizes:", lib[1:5], "\n")
