library(zellkonverter)
library(SingleCellExperiment)
library(Matrix)

cat("=== Test 1: use_hdf5=FALSE ===\n")
sce <- readH5AD("AIDA_RawCounts_ETHNICITY_v2.h5ad", use_hdf5=FALSE)
cat("dim:", dim(sce), "\n")
cat("assayNames:", assayNames(sce), "\n")
m <- assay(sce, 1)
cat("matrix class:", class(m)[1], "\n")
cat("matrix dim:", dim(m), "\n")
cat("Sum of all values:", sum(m), "\n")
cat("Max value:", max(m), "\n")
lib <- Matrix::colSums(m)
cat("Lib mean:", mean(lib), "  median:", median(lib), "\n")
cat("First 5 lib sizes:", lib[1:5], "\n\n")

cat("=== Test 2: use_hdf5=TRUE ===\n")
sce2 <- readH5AD("AIDA_RawCounts_ETHNICITY_v2.h5ad", use_hdf5=TRUE)
m2 <- assay(sce2, 1)
cat("matrix class:", class(m2)[1], "\n")
cat("Sum (TRUE):", sum(m2), "\n")
